require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout/AccessModifierIndentation:
  EnforcedStyle: indent

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true

Layout/DotPosition:
  EnforcedStyle: leading

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_ignore

Layout/LineLength:
  Max: 150
  IgnoreCopDirectives: true

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true

Lint/AmbiguousBlockAssociation:
  Exclude:
  - spec/**/*
  - lib/**/*

Lint/UselessAssignment:
  Exclude:
    - db/migrate/*.rb

Metrics/AbcSize:
  Exclude:
    - app/processes/**/*
    - /**/configuration.rb
    - db/migrate/*.rb
    - tagging/lib/**/*
    - app/read_models/*.rb

Metrics/BlockLength:
  CountAsOne: ['array', 'hash']
  IgnoredMethods:
    - class_methods
    - instance_methods
  Exclude:
  - config/routes.rb
  - config/environments/**/*
  - /**/spec/**/*

Metrics/ClassLength:
  CountAsOne: ['array', 'hash']

Metrics/CyclomaticComplexity:
  Exclude:
    - app/processes/**/*

Metrics/MethodLength:
  CountAsOne: ['array', 'hash']
  Exclude:
    - app/processes/**/*
    - /**/configuration.rb
    - tagging/lib/**/*

Metrics/ModuleLength:
  CountAsOne: ['array', 'hash']

Naming/AccessorMethodName:
  Exclude:
    - app/read_models/**/*

Naming/VariableNumber:
  CheckSymbols: false

Performance/Casecmp:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - describe
        - context
        - feature
        - example_group
        - endpoint
    Includes:
      Examples:
        - it_behaves_like
        - it_should_behave_like
        - include_examples
        - endpoint
    Helpers:
      - let
      - let!
      - set

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/FilePath:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/Alias:
  Enabled: false

Style/ArrayCoercion:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    detect: detect
    reduce: inject

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/EmptyBlock:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/EndlessMethod:
  EnforcedStyle: disallow

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/GlobalStdStream:
  Enabled: false

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/OptionalBooleanParameter:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "()"
    "%i": "()"
    "%I": "()"
    "%w": "()"
    "%W": "()"
    "%r": "{}"

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: false

Style/SafeNavigation:
  Enabled: false

Style/StabbyLambdaParentheses:
  EnforcedStyle: require_parentheses

Style/StringLiterals:
  Exclude:
    - db/migrate/*.rb

Style/SymbolArray:
  Exclude:
    - db/migrate/*.rb
