default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  port: 5432
  timeout: 5000
  database: free_stock_photo
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default
  database: free_stock_photo_test

staging:
  <<: *default

production:
  <<: *default
